### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [libpwquality/libpwquality#25]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by t8m** [comment]
[mandatory] which branch is your development branch?
**master**
[mandatory] have you merged latest translation from Zanata and locked the project?
**yes**
[optional] what is the license of translation?
Same as source code dual license: BSD-3-Clause or GPL-2.0-or-later

**Comment by Jibec** [comment]
Done: https://translate.stg.fedoraproject.org/projects/libpwquality/app/
please tell me which user should have admin rights on this project (you should connect at least once for me to see you)

Please note:
* LINGUAS file will be automatically updated by Weblate unless you ask me to disable it
* all po files will be automatically updated by Weblate, unless you ask me to disable it (this means before any po udpate, you'll have to manually merge translation, and then update po files with the new pot. If you don't, it will create conflicts)
* I activated git squash per author, if the pull request stays open, it will have effect, if not, you'll have more commits.

**Comment by t8m** [comment]
OK, thanks. My Fedora project user id is 'tmraz' - this should be the user with admin rights on the project.

**Comment by Jibec** [comment]
done, farewell
