### ISSUE TITLE
New password strings are untranslatable

### ISSUE THREAD

**Issue by piotrdrag** [libpwquality/libpwquality#3]
Strings in https://github.com/libpwquality/libpwquality/blob/master/src/pam_pwquality.c#L24 are not translatable to many languages. For example, in Polish we need to put %s%s after “password” for the sentence to make grammatical sense, which results in “Nowe hasło : ”, and that’s incorrect punctuation.

These strings should be split into two versions: one with “`<service>` ”, and one without.

The same issue is in https://github.com/linux-pam/linux-pam/issues/29

**Comment by t8m** [comment]
These are just omission from the previous versions of the code, now the prompting comes from Linux PAM. I'll remove them.
