### ISSUE TITLE
leaked_storage: Variable "auxerror" going out of scope leaks the storage it points to.

### ISSUE THREAD

**Issue by letoams** [libpwquality/libpwquality#47]
Error: RESOURCE_LEAK (CWE-772): [#def1]
libpwquality-1.4.4/python/pwquality.c:366: alloc_arg: "pwquality_read_config" allocates memory that is stored into "auxerror".
libpwquality-1.4.4/python/pwquality.c:370: leaked_storage: Variable "auxerror" going out of scope leaks the storage it points to.
  368|           }
  369|           Py_INCREF(Py_None);
  370|->         return Py_None;
  371|   }
  372|

**Comment by t8m** [comment]
This is not a bug. The API contract for this auxerror output argument is a little bit awkward but there is no leak if the API is used properly according to the documentation. And that is the case here.
