### ISSUE TITLE
  Password score differs from the one reported in cryptsetup

### ISSUE THREAD

**Issue by Ricky-Tigg** [libpwquality/libpwquality#48]
```
$ rpm -q cracklib libpwquality cryptsetup | column
cracklib-2.9.6-25.fc34.x86_64  libpwquality-1.4.4-2.fc34.x86_64  cryptsetup-2.3.5-2.fc34.x86_64
```
Password strength evaluation differs from the one implemented in _cryptsetup_; one reports _75_ the other reports _100_.
```
# cryptsetup luksFormat /dev/sdc1 --debug -v -c aes-xts-plain64 -h sha512 -s 512 -t 32 -T 8 --use-urandom -i 8192 --pbkdf argon2i --force-password --disable-keyring --integrity hmac-sha256 --label 0
[...]
# Checking new password using default pwquality settings.
# New password libpwquality score is 75.
[...]
```
```
$ echo "<password>" | pwscore
100
```

**Comment by t8m** [comment]
The strength score depends on settings. If cryptsetup changes some of the settings or uses different configuration file than the default one, it can report a different score.

**Comment by Ricky-Tigg** [comment]
`default pwquality settings` | Remains then your suggestion "_different configuration file_". Let's assume **it is** the case; we can then close.****
