### ISSUE TITLE
PWMAKE(1) | Unknown password entropy bit range values

### ISSUE THREAD

**Issue by Ricky-Tigg** [libpwquality/libpwquality#49]
_PWMAKE(1)_: Red Hat, Inc; **last updated:** 2017-02-10.

Some values – e.g 48 and 512 – may produce that message along with a password:
```
$ pwmake 48
Warning: Value 48 is outside of the allowed entropy range, adjusting it.
t4KENc@Jolow
```
Could the mentions of that range values be part of the `man` page? Would it be a bad idea to express it in the output? Example:
```
$ pwmake 48
Warning: Value 48 is outside of the allowed entropy range – 56–256. Adjusting it.
```

**Comment by t8m** [comment]
The range is quite prominently mentioned in the manual page. But yeah, pull requests welcome!

**Comment by Ricky-Tigg** [comment]
**No** match against keyword  _range_. One might see things that common mortals don't. Let's assume what you pretended to see is not meant to be see by others; we can then close.

**Comment by t8m** [comment]
You're right. It was not that prominent - actually the high limit was not mentioned.
Fix added.
