### ISSUE TITLE
Weblate | Translation not applied

### ISSUE THREAD

**Issue by Ricky-Tigg** [libpwquality/libpwquality#50]
**OS:** Linux Fedora; **Component:** libpwquality-1.4.4-2.fc34.x86_64

On the translation platform _Weblate_, under section dedicated to the Fedora organisation, the component located at _libpwquality/libpwquality_ is integrally translated into Finnish. Despite that state, in a Finnish language system, executed commands' outputs are still in the original language – English.

```
$ locale | head -1
LANG=fi_FI.UTF-8
```

**Comment by t8m** [comment]
Some of the messages come from the cracklib project.

Can you please show some of the untranslated output?
I cannot reproduce this on Fedora 32:

```
$ LANG=fi_FI.UTF-8 pwscore
wer
Salasanan laatutarkastus epäonnistui:
 Salasanan pituus on alle 8 merkkiä
```

**Comment by Ricky-Tigg** [comment]
Already illustrated | [#49]([url](https://github.com/libpwquality/libpwquality/issues/49)).

**Comment by t8m** [comment]
Ah, yes, that message is not yet translated in the repository in Finnish. Only in Weblate.

**Comment by Ricky-Tigg** [comment]
That does seem to me to be the way Weblate is intended to operate with this repository.  | [#25](https://github.com/libpwquality/libpwquality/issues/25)
