### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Thermi** [libpwquality/libpwquality#55]
Hello, when is the next release planned? I need a new release so I can get the fix for the pam issue I fixed in PR #53 into Alpine. Then it will work on Alpine.

**Comment by t8m** [comment]
I'd like to do it soon but I am quite busy with other things.

**Comment by t8m** [comment]
I'm sorry I did not get to release it earlier. Now it is done:
https://github.com/libpwquality/libpwquality/releases/tag/libpwquality-1.4.5
