### ISSUE TITLE
usercheck only works for usernames that are at least 4 characters long

### ISSUE THREAD

**Issue by jjfaith** [libpwquality/libpwquality#84]
The pwquality.conf manual page states:-
  usercheck=N
     If nonzero, check whether the password (with possible modifications) contains the user name in some form. It is not
     performed for user names shorter than 3 characters. (default 1)

But 3 character usernames which are NOT shorter than 3 characters are not checked.
This is because the usercheck function calls wordcheck(pwq,new,user) but at the start of wordcheck we have:-
  if (wordlen < PWQ_MIN_WORD_LENGTH)
                return 0;
In pwqpivate.h there is
  #define PWQ_MIN_WORD_LENGTH      4
So if username is < 4 characters long check is not done.

When the usercheck setting was added 
  https://github.com/libpwquality/libpwquality/commit/7c142370ea6fc6467bfae25fc7ff8fa12105591d
the manual was correct as the code was:-
#define PW_MIN_USERNAME_LEN_TO_CHECK 3
  if (userlen < PW_MIN_USERNAME_LEN_TO_CHECK)
        	return 0;

The functionality was changed by
  https://github.com/libpwquality/libpwquality/commit/6769b2a6fd146d5d6c3ada9aaac44a0e465ee6e7
  Use PWQ_MIN_WORD_LENGTH as minimum user name length to check. 

So the change appears to have been intentional but the manual was not updated to match.
Either the manual page should be changed to "It is not performed for user names shorter than 4 characters".
Or the code should be changed to match the manual page.

**Comment by t8m** [comment]
Fixed. Thank you for the report.
