### ISSUE TITLE
Don’t include alignment spaces in translatable strings

### ISSUE THREAD

**Issue by afranke** [libpwquality/libpwquality#93]
`"       The command reads the password to be scored from the standard input.\n"` in `src/pwscore.c` has spaces prefixed before the actual message. Can you please not include these, and concatenate them in the code? Otherwise it’s just error prone, as translators might omit them, or use a different number of spaces than intended. There is just no reason for translators to have to deal with them.

**Comment by t8m** [comment]
Hmm... but "fixing" this now means all translations have to be updated. Also, if any translator makes a mistake here in the number of spaces, no real harm is done. IMO this is not worth it. I've added a TODO comment to fix this if we ever change the text.
